[package]
name = "yearfrac"
version = "0.1.0"
edition = "2021"
authors = ["Anatoly Bugakov"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
thiserror = "1.0.30"
backtrace = "0.3"
